<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" Version="2.9.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldMap.Core.Shared\WorldMap.Core.Shared.csproj" />
    <ProjectReference Include="..\WorldMap.Application\WorldMap.Application.csproj" />
  </ItemGroup>

</Project>
