<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ObjectsLayer\Building\**" />
    <EmbeddedResource Remove="ObjectsLayer\Building\**" />
    <None Remove="ObjectsLayer\Building\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WorldMap.Domain\WorldMap.Domain.csproj" />
  </ItemGroup>

</Project>
